version: "3.9"
services:
  cli:
    build: cli
    networks:
      - codespaces
    volumes:
      - ..:/workspaces/snipe-it
    env_file:
    - .env.docker


  fpm:
    build: fpm
    networks:
      - codespaces
    volumes:
      - ..:/workspaces/snipe-it
    user: 1000:1000
    env_file:
    - .env.docker

  nginx:
    build: nginx
    networks:
      - codespaces
    volumes:
      - ..:/workspaces/snipe-it
    ports:
      - 8000:8000
    depends_on:
      - fpm
    env_file:
    - .env.docker

  mariadb:
    build: mariadb
    networks:
      - codespaces
    volumes:
    - ./.db:/var/lib/mysql
    env_file:
    - .env.docker
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2-alpine
    networks:
      - codespaces


networks:
  codespaces: {}
