version: "3.9"
services:
  cli:
    build: cli
    volumes:
      - ..:/workspaces/snipe-it
    env_file:
    - .env.docker

    
  fpm:
    build: fpm
    volumes:
      - ..:/workspaces/snipe-it
    user: 1000:1000
    env_file:
    - .env.docker

  nginx:
    build: nginx
    volumes:
      - ..:/workspaces/snipe-it
    ports:
      - 8000:80
    depends_on:
      - fpm
    env_file:
    - .env.docker

  mariadb:
    image: mariadb:10.6.4-focal
    volumes:
    - db:/var/lib/mysql
    env_file:
    - .env.docker
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2-alpine

volumes:
  db: {}